# Example Home Assistant configuration file for reference.
#
# The Victron Cloud integration is configured from the UI and does not
# require any YAML entries. This file exists only to keep Home Assistant's
# default example sections available for users who want to copy them.

default_config:

# Additional integrations (themes, automations, scripts, scenes) can be
# included here as needed.
